-- Opportunity payload, Phase 2 — give `opportunity_evidence` the UNIQUE index
-- its writer needs.
--
-- The table has existed since 0000_init with two foreign keys and one plain
-- index (`opportunity_evidence_opp_ix` on `opportunity_id`, 0000_init.sql:288),
-- but NO UNIQUE INDEX and no primary key. It has sat at 0 rows for its whole
-- life, so nothing ever exercised the write path and nothing surfaced the gap.
--
-- That matters now because the evidence linker walks
-- `opportunities.project_id` -> `record_resolutions` -> `evidence_items` and
-- re-sees the same (opportunity, evidence item) pair on every run. Its write
-- path is INSERT ... ON CONFLICT DO NOTHING, and ON CONFLICT REQUIRES A UNIQUE
-- INDEX to name as its arbiter — without one the statement does not merely
-- duplicate rows, it fails outright with "no unique or exclusion constraint
-- matching the ON CONFLICT specification".
--
-- Uniqueness is per (opportunity, evidence item): one evidence item supports one
-- opportunity once. The same evidence item legitimately supports MANY
-- opportunities — several accounts can be chasing the same project — so the
-- constraint is deliberately on the pair and never on `evidence_item_id` alone.
--
-- THE OLDER INDEX IS NOT REDUNDANT — DO NOT DROP IT. It is tempting to think so,
-- because `opportunity_id` leads this new index and a leading column can serve
-- lookups on its own. Measured on the populated table, that reasoning is wrong:
--
--   SELECT claim_type, confirmed, confidence ... WHERE opportunity_id = $1
--     -> Index Scan using opportunity_evidence_opp_ix
--
-- The planner picks the OLD index because this unique index does not COVER those
-- columns, and at 4,504 kB against 960 kB it is 4.7x more index to traverse for
-- the same heap fetches. That query is exactly the read this data exists for —
-- rendering an opportunity's evidence.
--
-- This index still wins wherever it covers the projection:
--
--   SELECT opportunity_id, evidence_item_id WHERE opportunity_id IN (...)
--     -> Index Only Scan using opportunity_evidence_opp_item_ux, Heap Fetches: 0
--
-- Two indexes, two access patterns, both earning their keep.
--
-- IF NOT EXISTS so a re-run against an environment that already has the index is
-- a no-op rather than an error.
CREATE UNIQUE INDEX IF NOT EXISTS opportunity_evidence_opp_item_ux
  ON opportunity_evidence (opportunity_id, evidence_item_id);
